spring:
  application:
    name: EmployeeZuul
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
zuul:
  routes:
    foos:
      path: /employee/**
      url: http://localhost:8081/employeezuul/employee