spring:
  application:
    name: EmployeeDetail
  jpa:
    show-sql: false
server:
  port: 0
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2