spring:
  jpa:
    show-sql: true
  application:
    name: EmployeeDetail
server:
  port: 8091
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
