server:  
  port: 9000

spring:  
  application:
    name: Employee Detail

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true