server:  
  port: 9000

spring:  
  application:
    name: Employee Address

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true