server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: EmployeeEureka
  thymeleaf:
    enabled: false 
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
